// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sokol-logo/NeonRing.tsx": () => import("../components/mockups/sokol-logo/NeonRing.tsx"),
  "./components/mockups/sokol-logo/OrbitLens.tsx": () => import("../components/mockups/sokol-logo/OrbitLens.tsx"),
  "./components/mockups/sokol-logo/SignalArc.tsx": () => import("../components/mockups/sokol-logo/SignalArc.tsx"),
  "./components/mockups/sokol-eagle/EagleFlight.tsx": () => import("../components/mockups/sokol-eagle/EagleFlight.tsx"),
  "./components/mockups/sokol-eagle/EagleHeraldic.tsx": () => import("../components/mockups/sokol-eagle/EagleHeraldic.tsx"),
  "./components/mockups/sokol-eagle/EagleOutline.tsx": () => import("../components/mockups/sokol-eagle/EagleOutline.tsx"),
  "./components/mockups/sokol-eagle/OriginalEagleStudy.tsx": () => import("../components/mockups/sokol-eagle/OriginalEagleStudy.tsx")
};
